export const CIRCLE_TEXTURE_SIZE = 512;

// Circle_01 的 A 恒为 255、R 恒等于 B，并且纹理关于主对角线逐像素对称。
// 直接保存上三角的 (长度, R, G) 游程，避免调色板索引近似原始 texel。
const RUNS_BASE64_CHUNKS = Object.freeze(
  [
    '/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAAEgAABAIBCAAC/wAA0QAABAAEBAgIBAgMEBAMBAgMBAgIBAgE/wAAuQAAAw0MBBAOBBAUBBgZBBsdBCAdDCAfBBsdBBgZBBgUBBAQBA0NAQsK/wAApQAAAQUFBAgIAwsKARYVBBsYBCAdBCAkBCgqBC4vBDEvDDEyBC4vBCgqBCgkBCAgBBsaAhYVAgsKARAQAwgIAgUF/wAAlQAAAQICAQUFAQgIAgoKAxAQAxgYBCEgBCkkBDEsBDE0BDk8CEJBDEJFBEJBBDk8BDk0BDEwBCkoBCEgBBgYAxAQAQoKAggIAQUFAQIC/wAAiQAABAgEBBAMBBgYBCEkBDEwBDk4BEJBBEpNBFpZBGNhBGNlDGtpBGNhBFpZBEpNBEJBBDk8BDEwBCkoBCEcBBAQBAgI/wAAgQAAAw0NBBgUBCMgBCssBDc4BEREBE9NBGVlAkpNAnZ4BFpZBGNhBGNlDGtpBGNhBFpZA3Z4AUpNBGtpBFJUBEdHBDw8BDQwBCMkBBgZAw0O/wAAeQAAAwsJAQ0NAxsaARgUAygkBDY0BD5ABE1MBFdYBGVjBGVlBHZ4BImHBJSTBJeXDJybBJSUBImIBHZ4BGtpBGttBF1eBE9QBEdEBDY4BCgqAxsdAQ0OARYVAwsKAQUF/wAAbQAAAQUEAgoIARAMAxYSASEcARsaAykoBDk0BEpJBFJVBGNhBGttBHt5AYmJA62uBM7PBOfjBPf3BP/7DP//BPf7BOfnBM7PAr26ApSRBISGBHN1BGNlBFpZBEpNBDk8BCksAiEgAhYVAhAQAQoKAgUFAQIC/wAAYwAAAwAEARYWAxAQASYlAyEkATc5AzE0AUlMBEpFBFJVBGttBHt5ApSWAre5Ac7LAt7cAe7tAffzAfz7Lf//Afz9AfT0AenpAt7fAsPBAqWiBISCBHNxBGNhBEpNBDk8BCkoASspAxgUBAgI/wAAXgAAAg0NBBYWBCYlBDc5BElMAkpFAnZ0AVJVA4mJAmttApycAaekAtPPAf/7QP//Av/7AtbSAcvNAp+fAXNxAZSUA2NhAn6AAkpNA1pbATk8BD89BCspBBsbAw0O/wAAVgAAAggIAg0NAhsaARYWAywpBDw7BE1PBGJkBHZ0AomJAsC+Ac3LB//7QP//BP/7BPf7A8XHAZSUBH6AAXt6A1pbBFVTBD4/Ay4uARsbAxsdAQ0OARAQAggI/wAATQAAAQICAQUFAQgIAhAQARgYAhsaAikoASwpA0I8ATw7A1JRBGNlBHt9AqKjAs7TBPfzCP/7QP//BP/7CPf7A+fnAbKzAZyaA3t6BGtpBFJVA0JBAS4uAyksARsdAhgYAhAQAQgIAQUFAQIC/wAARgAAAwgIARscAxgcATExAiksAkFEBEpNBGNhA3N1AaGjAa2qAcjGAuPiAfz9YP//AezrAdnXAcbDAqGjAnN1BGtpBFJRAVJTAzE0ATc3AyEgBBAM/wAAQgAAAg0NBBscBDExA0FEAVpcAkpNAnt8AmNhApSUAaGjAtDRa///AtDRApyZAmtpAYOEA1JRBFJTBDc3AyMfARAMAxAQ/wAAOgAAAggGAg0NAhsaARscAy4wATExA0pHBFpcBHt8AZSUAsXHAff7cP//Av/7As3KAbW3A4OEAnNyAlJTA01OATc3AzYyASMfAiAgAxAQAQgI/wAANAAAAggGARANARgUAhsaAikoAi4wAkJFAkpHAmNdBHN1AqyrAt7bBPf7cP//BP/7A+frAbW3AZSSA3NyA2NlAU1OA0pFATYyAjEwAiAgAhgYARAQAQgIAQUFAQIC/wAAKwAAAwAEARMVAhAUAigrAiksAkFEBFJRBGttAXt5AaelAtPSAffzgP//Ad7eAb2+AZyeBHt5BFJRAVJTAzE0ATczAyEcAhYYAgAE/wAAJwAAAQsJBBMVAygrAUFCA0FEAVpcA1JRAYODAmttAZmcAcjLAdPSh///AtPSAaelAXt5AoaFAlJRBFJTAzczASEcASwsAxYYAgsM/wAAIgAAAgsJARYSARMVAyYmASgrA0FCA1pcAXN1A4ODAbW1AcjLA/f7i///AdPSArq6AoaFAnNyAlJTA01KATczAywsAxYYAgsMAQUE/wAAGwAAAQUFAQgIAQsJARYSAiEcASYmAzk4AUFCA1pZAVpcA3N1ArW1AufnBPf7jP//A+/vAbq6AZSSA3NyAmNhAk1KA0JBASwsAiEkAhYYARAMAQoIAQUE/wAAFgAAAwgIARscAyEkATk7BEJBBGNlAXt9AqeoAdPTAff3mP//AdvcAbe5AZSWBGttBEpNAjw9AiEkAiAjAggM/wAAEgAAAg0MAxscAS4wASEkAzk7AkJBAnBxAmNlApSVAdPTn///Ac3LApycAWttAnt8AkpNAVdXAzw9ATk6AyAjAg0O/wAADAAAAQUEAg0MAhsYARscAy4wATk7A1JSBHBxAZSVAcXGAvf3oP//A//7Ac3LAayrA3t8A1dXATw9Azk6ASAjAhsdAg0OAgUF/wAABQAAAQUEAQoIARAMAhsYAikkAi4wAkJFAlJSAmtpAnBxAZ+iAc7TBPf3oP//BP/7At7bAayrAXt8A3NxAVdXAlJRAjk6AiksAhsdAhAQAQoKAQUF/wAAAQAAAggIAh4fAiEkAjw9BEpNA3NxAaGfAb2+Aenprf//AefnAdDNAaGfAnNxBFJRAkRHAiksAiYnAhAQARAO/AAAAg0OAx4fATQ2Azw9AVdXAkpNAn5/AXNxAaGfAdDNAf/7sP//Av/7AdDNAaGfAomIAlJRAV9iA0RHATw+AyYnAxAO9gAAAQUEAw0OARsdAR4fAzQ2ATw9A1dXA35/AbKxAdDNA//7sP//BP/7AsC/AomIA19iAURHAzw+ASYnAiAdAhAOAgUG8QAAAQUEARAMAQ0OAhsdASksAjQ2AkpNAldXAnNxAX5/AbKxAufjBP/7sP//BP/7A/f3AcC/Ant9Al9iAlJVAjw+AjEsAiAdARAUAQoNAQUG7QAAAggEAh4ZAiEkAjw9BEpJAmNlAZSVAcXGAefn',
    'v///AdPPAaekAnt5BFpdAkpLAiksASgpAxAU6gAAAQsMAx4ZATQvAzw9AVdXAkpJAoGAAZSVAcXGAvf3wP//A//7AdPPAouPAlpdBEpLAygpARAUAhAQ5QAAAgsMARYYAR4ZAzQvATw9A1dXA4GAAbi3BPf3wP//BP/7Ae/zAb3BAouPAmtqAkpLAkE/AigpASAgAxAQAQUE3gAAAQICAQgIAQsMARYYAiEkAjQvAkpFAldXAnNxAYGAAbi3Au/vBPf3wP//BP/7A+/zAb3BAYyKA2tqAlpVAkE/ATEwAiAgARAQARAMAQoI2gAAAgAEAhMWAiEcAjk1BEpNA3N1AdDRAe/r0P//AaeoAnt9AYODA0pJAkE/AikkAh4bAggE1wAAAQAEAhMWASYpASEcAjk1AVJPAkpNAn6AAXN1AaGjAdDR0///AdPTAaeoA4ODAUpJAVpaA0E/ATQyAx4bAQsM0wAAAQgIARAQARMWAiYpATk8ATk1A1JPA36AAbKzAdDR1///Aff3Ab29AoODAXN1AlpaAUE/AzQyAR4bARYYAgsMzgAAAQgIAhAQARgYAiYpAjk8AlJPAmtpAX6AAbKzAufn2P//Avf3Ar29AnN1AlpaAkpJAjQyASEkAhYYAQsMAQUFygAAAQ0OAhAQAispAzk8AWhpA2tpAZyZAc7P3v//Aff3AdDOAaGhAnN1BEpJAjExAhgYARAUAwAExQAAAQ0OARsdAyspAUdDAjk8AmhpAmtpAc3KAf/74P//Av/7AdDOAXN1AoF/AkpJAUpLAzExASAkAhAUAQAEwQAAAQUEAg0OAhsdAispAkdDBGhpAZyZAc3KAv/74P//A//7AdDOAbi1AoF/AUpJAWNlAkpLATExATE0AiAkARAUAggGvQAAAQUEARAMAhsdAiksAkdDAmNdAmhpAZeWAcbDBP/74P//BP/7Ae/rAbi1AoF/AmNlAkpLAjE0AiAkARgUARANAQgGuQAAAgAEAhgZAikkAkE/A1pZAYuLAYyKAbKx7P//AenoAb26AZSTA2NhAlRXAjE0Ah4hAggMtgAAAQgJAxgZATEvASkkAkE/AVpaAlpZAYuLAb29AdjY7///AcXFAZSTAmNhA1RXATE0ATQ3Ax4hAQ0MswAAAQgJARASAhgZAjEvAUE/AlpaAXN1AouLAb29Ae/v8P//Avf3AcXFAZSTAnh6AlRXAUpNAjQ3AR4hARsYAg0MrgAAAggJARASARgcAjEvAkpFAlpaAnN1Ab29A+/v8P//BPf3AZyeAnh6AVRXAkpNAjQ3ASkkAhsYAQ0MAQUFqgAAAQ0NAhAUAigsA0JBAXNxAmttAZmcAcjLAff3+P//AdPTAnt9AXl7A0JFAjc3AiEgARMSqAAAAg0NARAUAigsAUFEAkJBAnNxAWttAZmcAvf7+v//AdPTAaeoA3l7AUJFAU1OAjc3ASEgAxMSpAAAAQ0NAhsaAigsAkFEAUJBA3NxAcjLA/f7/P//AbCxA3l7AWNlAU1OAjc3AiYlAhMSAQUEnwAAAQgIAQ0NARsaAikoAkFEAlpdAnNxAaSiAdbTBPf7/P//AufnAbCxAXl7AmNlAk1OATk4AiYlARMSARAMAQoInAAAAhARAiEgAjk4A0pNAYGDAXt5AdPS////Bf//AezrAcbDAomLAlJVAkREAikoAh4dAggImAAAAhARASAiASEgAjk4AVJQAUpNA4GDAdPS////CP//AcDBAomLAVJVAV9gAkREASkoATQzAh4dAggIlAAAAQUFAhARASAiATE0Ajk4AVJQAWtpAoGDAbi5Ae/v////Cf//Avf3AcDBAYmLAl9gAkREAjQzAh4dARAQAQgIkQAAAQoKARAQAiAiAjE0AlJQAmtpAYGDAbi5Au/v////Cf//A/f3AcDBAnt9Al9gAUpJAjQzAR4dARgYARAQAQgIjQAAAggIAh4dAjEsAk9LA2NlAZSXAd7b////EP//AdDNAaGfAnNxAWhmAzk4AiMkAggMiwAAAQgIAh4dATQzATEsAk9LAW1qAmNlAZSXAff7////Ef//Av/7AaGfAXNxA2hmATk4AT48AiMkAQgMAQsMhwAAAQgIARAQAh4dAjQzAk9LAm1qAZSXAcXJAvf7////Ef//A//7AdDNBGhmAj48AiMkARYYAgsMgwAAAQgIARAQARgYAR4dAjQzAUpJAU9LAm1qAYyKAcXJA/f7////Ef//BP/7AcbDAZeUAmhmAVpVAj48ASMkASEkARYYAgsMgAAAAhAMAiYjAjE0Al9iAnN1AaGjAdDR////Gv//AdPTAaeoAXt9Anh3Ajk4AjEwAhgYAQ0NfQAAAQsKARAMAiYjATw6ATE0A19iAXN1AaGj////Hv//AaeoA3h3ATk4AUpIAjEwARgYAg0NegAAAQsKARYVAiYjAjw6A19iAY6QAdDR////IP//Abe3A3h3AkpIAjEwARsaAg0NdwAAAQsKARYVASEgASYjAjw6AVJRAl9iAY6QAb2+////If//Aff3Abe3Anh3AWNhAkpIATEwASkoAhsaAQ0NAQAEcwAAAhAUAigrA0JBAXZ1AXNxAaGgAdDP////JP//AdvaAZSSAYOEA1JRAjk1AiEcARAOcQAAAQsMARAUAigrAUFCAkJBAnZ1AaGgAdDP////Jv//AdvaAbW3AYOEAlJRAVJPAjk1ASEcASAdARAObQAAAgsMARYYAigrAkFCAUJBAnZ1Aaqq////Kf//AefrAbW3AYOEAVJRAlJPAjk1AiAdARAOagAAAgsMARYYASEkASgrAkFCAVpZAnZ1AaqqAd7f////Kf//AufrAbW3AYOEAWtpAlJPATk1ATEsAiAdARAOAQUFZwAAAhgUAjEsA0pNAYOEAYSCAa2r////Lv//Ab26AoOEAkpJAjw7AiEgARAQZAAAAg0MARgUAjEsAUpEAkpNAoOEAa2r////MP//Ab2/AoOEAUpJAVdWAjw7ASEgASAgARAQYQAAAg0MARsYAjEsAkpEAUpNAoOEAb27////Mf//Aff7Ab2/AoOEAldWAjw7AiAgARAQXgAAAg0MARsYASkkATEsAkpEAWNdAoOEAb27Affz////Mf//Avf7Ab2/AYOEAXNxAldWATw7ATEwAiAgARAQAQgIWwAAAhgYAjEwA1JRAYuLAYSGAdbW////Nv//AdbXAouLAlJRAjw9AiEkARAQWwAAAjEwAUpI',
    'AlJRAouLAdbW////OP//AcXFAouLAVJRAVdXAjw9ASEkASAgARAQWgAAAkpIAVJRAouLAcXF////Ov//AcXFAouLAldXAjw9AiAgARAQWQAAAWNhAouLAcXF////PP//AcXFAYuLAXNxAldXATw9ATEwAiAgARAQAQUFVwAAAYyOAdjZ////Pv//Ad7bAouLAlJRAjw7AiEgAQ0OVwAA////QP//AcXFAouLAVJRAVdWAjw7ASEgARsdAQ0OVgAA////QP//AcXFAouLAldWAjw7ASksARsdAQ0OVQAA////QP//AcXFAYuLAXNxAldWATw7AiksARsdAQ0OAQAEUwAA////QP//Ad7bAouJAlJRAjk3AiEcAQ0NUwAA////QP//AcXCAouJAVJRAVJSAjk3ASEcARsaAQ0NUgAA////P///Af/7AcXCAYuJAVJRAlJSAjk3ASkoARsaAQ0NUQAA////Pv//Av/7AcXCAYuJAWttAlJSATk3ASkoARsaAg0NUAAA////QP//Ab3DAoGDAkpNAURGAS4vAhgYAQ0MTwAA////QP//Abi5AoGDAUpNAURGAi4vARgYAg0MTgAA////P///Ae/vAbi5AoGDAVpdAURGAi4vARsYAQ0MTgAA////Pv//Au/vAbi5AYGDAlpdAURGAS4vASkkARsYAQ0MTQAA////P///AeHgAaWiAYOEA0pJATw+ASYnAhAQTAAA////P///AeHgAoOEAkpJATw+AiYnARAQAQgJSwAA////P///Ab2/AoOEAUpJAVJVATw+AiYnARASAQgJSgAA////Pv//Aff7Ab2/AoOEAlJVATw+ASYnARgcARASAQgJSQAA////Pf//Av/7AdPRAXt9Am5vAkJBAh4cAggISAAA////PP//A//7AaenAm5vAkJBATQwAh4cAQgIAQUFRwAA////O///BP/7AZqdAm5vAUJBAUpFATQwAh4cAQoKRwAA////Ov//BP/7AcbLAZqdAm5vAUpFAjQwAR4cARAQAQUFRgAA////Pf//Af/7AdDOAnN1Ak9OAjEwASYiARMRRgAA////PP//Av/7AdDOAXN1AW1sAk9OATEwASYiAhMRRQAA////O///A//7AaGhAm1sAk9OATk0ASYiAhMRRAAA////Ov//BP/7AYyKAm1sAU9OATk0AiYiARMRAQgIQwAA////Pf//AcXJAZSXAmNlAVJQATk4AiEgAQ0OQwAA////PP//Aff7AcXJAmNlAVJQAjk4ASEgARsdAQ0OQgAA////O///Avf7AZSXAWNlAWtpAVJQAjk4ARsdAg0OQQAA////Ov//A/f7AZSXAmtpAVJQATk4ASksARsdAQ0OQQAA////PP//AdbXAYaHA1JRATw/ASYpAhAUQAAA////PP//Abq9AYaHAlJRATw/AiYpARAUAQgIPwAA////O///Ae/zAbq9AYaHAVJRAVJVATw/AiYpARAQAQgIPgAA////Ov//Au/zAoaHAlJVATw/ASYpARgYARAQPgAA////O///AdPTAXt9AmVmAjk8ASYpARMWAgAEPAAA////O///AaeoA2VmATk8AiYpARMWAQAEPAAA////Ov//AdPTAZGQAmVmAjk8ASYpAhMWAQICOwAA////Ov//Ab26AZGQAmVmAjk8ASYpARMWAQgIOwAA////Of//Aff7AZmcAmttAVJSATk7AiEkAQ0NOwAA////OP//Avf7AZmcAWttAlJSATk7ASEkARsaAQ0NOgAA////N///Avf7AcjLAWttAWtpAVJSAjk7ASkoAg0NOQAA////Nv//A/f7AZmcAmtpAVJSATk7ASkoARsaAQ0NOQAA////OP//Ad7bAoGBAkpJATQ3Ah4hAQgMOAAA////OP//Abi6AYGBAkpJAjQ3AR4hAQgMAQUGNwAA////N///Ae/zAoGBAUpJAUpNATQ3Ah4hAQoNNwAA////Nv//Ae/zAbi6AoGBAkpNATQ3AR4hARAUAQUGNgAA////Nf//Av/7AaekAXt5AWttAkpMASksASAkARAUAgAENAAA////NP//Av/7AdPPAXt5AWttAkpMASksASAkARAUAgAENAAA////M///A//7AaekAmttAkpMATE0ASAkARAUAQAENAAA////Mv//BP/7AYyOAmttAUpMATE0ASAkAhAUNAAA////Nf//AcLBAY6LAlpVAUFCAigrARAUAQgIMwAA////NP//Aff3Ao6LAVpVAkFCASgrARAUARAQMwAA////M///Aff3AcLBAY6LAVpVAVpZAUFCAigrARAQAQgIMgAA////Mv//Avf3AcLBAY6LAVpZAkFCASgrARgYARAQMgAA////M///AdjYAYyKAl9gAjk8ASYmARMVAgAEMAAA////M///AbKxAYaFAl9gATk8ASYmAhMVAQAEMAAA////Mv//AdjYAYaFAl9gATk8ATk4ASYmARMVAQAEMAAA////Mv//Aa2qAYaFAl9gATk4ASYmAhMVMAAA////Mf//Aff3AY6QAlpdAUREAS4wAhgcAQgILwAA////MP//Aff3AcLDAY6QAVpdAVpZAUREAS4wARgcARAQLwAA////L///Avf3AY6QAVpdAVpZAUREAS4wARgcARgYAQgILgAA////Lv//Avf3AcLDAY6QAlpZAUREAS4wARgYARAQLgAA////L///Ad7dAZyaAmJjAjk8ASYmARMVAgAELAAA////L///Ab27AYuKAmJjATk8ASYmAhMVAQAELAAA////Lv//Ad7dAYuKAmJjATk8ATk4ASYmARMVAQAELAAA////Lv//AbWyAYuKAWJjATk8ATk4ASYmAhMVLAAA////Lf//Aff3AY6QAlpdAUREAS4sAhgUAQgIKwAA////LP//Aff3AcLDAY6QAVpdAkREAS4sARgUAQgIKwAA////K///Avf3AY6QAlpdAUREAS4sARgUARAQAQgIKgAA////Kv//Avf3AcLDAlpdAUREAi4sARgYAQgIKgAA////K///AdPTAXt9AWttAkpMASksASAdARAOKgAA////K///AaeoAmttAUpMASksASAdAhAOKQAA////Kv//AdPTAmttAkpMATEsASAdARAOKQAA////Kv//AYyOAWttAkpMATEsASAdARAOKQAA////Kf//Abq9AYaHAlJRATQ3Ah4hAQgMKAAA',
    '////KP//Ae/zAYaHAlJRAUpNATQ3AR4hAQgMAQUEJwAA////J///Ae/zAbq9AYaHAVJRAUpNATQ3Ah4hAQoIJwAA////Jv//Au/zAYaHAVJRAUpNAjQ3AR4hARAMAQUEJgAA////J///AaGgAXNxAVdXAjw9ASEkARYVAQsKJgAA////Jv//AdDPAXNxAldXATw9ASEkARYVAQsKJgAA////Jf//AdDPAnNxAVdXAjw9ASEgAQsKJgAA////Jf//AaGgAXNxAVdXAjw9ASEgARYVAQsKJQAA////JP//AdbXAnN0AkJFASYpAhMWAQAEJAAA////I///AfHxAaSjAXN0AkJFATk8ASYpARMWAQAEJAAA////I///AaSjAnN0AUJFATk8ASYpARMWAQAEJAAA////Iv//AdbTAnN0AUJFATk8ASYpAhMWJAAA////If//Aff3AZSTAmNhAUFAAigoARAQAQUFIwAA////IP//Aff3AcXFAmNhAkFAASgoARAQAQoKIwAA////H///Avf3AZSTAWNhAVpZAUFAAigoARAQAQUFIgAA////Hv//Avf3AZSTAWNhAVpZAUFAAigoARAQAQUFIgAA////H///AdPSAXt5AVpaAkFDASksARYYAQsMIgAA////Hv//AdPSAXt5AXNxAVpaAUFDASksASEkAQsMIgAA////Hv//AaelAXNxAVpaAUFDASksASEkARYYAQsMIQAA////Hf//AdPSAXNxAVpaAkFDASEkARYYAQsMIQAA////HP//AefnAnN1AkJFASYmAhMVAQAEIAAA////G///Aff3AaSmAXN1AkJFATk4ASYmARMVAQAEIAAA////G///AdbXAnN1AUJFATk4ASYmARMVAQAEIAAA////Gv//AdbXAnN1AUJFATk4ASYmAhMVIAAA////Gf//Aff3AZSTAmNhATw7AiYlARAQAQUEHwAA////GP//Aff3AcXFAmNhAVJRATw7ASYlARAQAQUEHwAA////F///Aff3AcXFAmNhAVJRATw7ASYlARAQAQoIHwAA////Fv//Avf3AZSTAWNhAVJRATw7AiYlARAMHwAA////Ff//Av/7AaGfAXNxAVJPAjk5ASEkARYSHwAA////FP//Av/7AdDNAXNxAWtlAVJPATk5ASEkARYSAQsJHgAA////E///Av/7AdDNAXNxAWtlAVJPATk5ASEkARYSAQsJHgAA////Ev//A//7AaGfAWtlAVJPAjk5ASEcAQsJHgAA////FP//Aa2uAXBuAVRTAjk4ARsdAQ0OHgAA////E///AcjJAXBuAlRTATk4ASksARsdAQ0OHQAA////Ev//AePkAnBuAVRTATk4ASksARsdAQ0OHQAA////Ef//AePkAYyKAXBuAVRTATk4ASksARsdAQ0OHQAA////Ef//AayuAXt9AkpNATk8ASgpARgWAQgEHAAA////EP//AayuAXt9AkpNATk8ASgpARgWAQgEHAAA////D///Ad7fAnt9AUpNATk8ASgpARgWAQgEHAAA////Dv//Ad7fAnt9AUpNATk8ASgpARgWAQgEHAAA////Df//Af/7AZeUAmNhAUpNATY6ASMnARAUAQICGwAA////DP//Af/7AcvHAmNhAUpNATY6ASMnARAUAQUFGwAA////C///Af/7AcvHAmNhAUpNATY6ASMnARAUAQgIGwAA////Cv//Af/7AcvHAZeUAWNhAUpNATY6ASMnARAUAQgIGwAA////Cf//Av/7AnNxAVpdAUdIATQ0ASEgAQoNGwAA////CP//Av/7AaGfAXNxAVpdAUdIATQ0ASEgARAUAQUGGgAA////B///Av/7AaGfAXNxAVpdAUdIATQ0ASEgARAUAQUGGgAA////Bv//Av/7AdDNAXNxAVpdAUdIATQ0ASEgARAUAQUGGgAA////Bf//Av/7AdPRAXt9AWttAVVXAT9BASksARYVAQsKGgAA////BP//A//7AXt9AWttAVVXAT9BASksARYVAQsKGgAA////A///A//7AaenAWttAVVXAT9BASksASEgAQsKGgAA////Av//A//7AaenAWttAVVXAT9BASksASEgAQsKGgAA////BP//Ab26AXt9AWVmAU9PATk4ASEkARYYAQsMGQAA////A///AdPRAXt9AWVmAU9PATk4ASEkARYYAQsMGQAA////Av//AdPRAXt9AWVmAU9PATk4ASEkARYYAQsMGQAA////Af//AenoAXt9AWVmAU9PATk4ASEkARYYAQsMGQAA////AffzAY6QAWhqAkJFATEwASAgARAQGQAA/v//Afz7AY6QAmhqAUJFATEwASAgARAQGQAA/v//AbW2AmhqAUJFATEwASAgARAQGQAA/f//AbW2AmhqAUJFATEwASAgARAQGQAA/P//Ad7jAYCBAlJRATk4ASgoARgYAQgIGAAA+///Ad7jAYCBAlJRATk4ASgoARgYAQgIGAAA+v//Ad7jAYCBAlJRATk4ASgoARgYAQgIGAAA+f//Ad7jAYCBAlJRATk4ASgoARgYAQgIGAAA+P//Aff3AY6NAlpZAUJBATEvASAdARAMAQABFwAA9///Aff3AY6NAlpZAUJBATEvASAdARAMAQABFwAA9v//Aff3AY6NAlpZAUJBATEvASAdARAMAQACFwAA9f//Aff3AcLCAlpZAUJBATEvASAdARAMAQAEFwAA9P//Af/7AcjFAlpZAUpJATY2ASMjARAQAQUFFwAA8///Af/7AcjFAZGPAVpZAUpJATY2ASMjARAQAQUFFwAA8v//Af/7AcjFAZGPAVpZAUpJATY2ASMjARAQAQUFFwAA8f//Af/7AcjFAZGPAVpZAUpJATY2ASMjARAQAQgIFwAA8P//Aff3AcXGAmNlAVJRAT4+ASsrARgYAQgIFwAA7///Avf3AZSVAWNlAVJRAT4+ASsrARgYAQgIFwAA7v//Avf3AZSVAWNlAVJRAT4+ASsrARgYAQgIFwAA7f//Avf3AZSVAWNlAVJRAT4+ASsrARgYAQgIFwAA7P//Avf7AZmZAWtpAVJVAT5AASssARgYAQoIFwAA6///Avf7AZmZAWtpAVJVAT5AASssARgYAQoIFwAA6v//Avf7AZmZAWtpAVJVAT5AASssARgYARAMFwAA6f//Avf7AZmZAWtpAVJVAT5AASss',
    'ARgYARAMFwAA6v//AaGgAXNxAVpZAUdEATQwASEcARAMFwAA6f//AaGgAXNxAVpZAUdEATQwASEcARAMFwAA6P//AaGgAXNxAVpZAUdEATQwASEcARAMFwAA5///AaGgAXNxAVpZAUdEATQwASEcARAMAQUEFgAA5v//AaGjAXN1AVpZAUdEATQwASEcARAMAQUEFgAA5f//AaGjAXN1AVpZAUdEATQwASEcARAMAQUEFgAA5P//AaGjAXN1AVpZAUdEATQwASEcARAMAQUEFgAA4///AaGjAXN1AVpZAUdEATQwASEcARAMAQUEFgAA4v//AaGjAXN1AVpZAUdEATQwASEcARAMAQUEFgAA4f//AaGjAXN1AVpZAUdEATQwASEcARAMAQUEFgAA4P//AaGjAXN1AVpZAUdEATQwASEcARAMAQUEFgAA3///AaGjAXN1AVpZAUdEATQwASEcARAMAQUEFgAA3v//AaGjAXN1AVpZAUdEATQwASEcARAMAQUEFgAA3f//AaGjAXN1AVpZAUdEATQwASEcARAMAQUEFgAA3P//AaGjAXN1AVpZAUdEATQwASEcARAMFwAA2///AaGjAXN1AVpZAUdEATQwASEcARAMFwAA2P//Av/7AZyZAWtpAVJVAT5CASsvARgcARAMFwAA1///Av/7AZyZAWtpAVJVAT5CASsvARgcARAMFwAA1v//Av/7AZyZAWtpAVJVAT5CASsvARgcARAMFwAA1f//Av/7AZyZAWtpAVJVAT5CASsvARgcAQoIFwAA1P//Au/zAZGPAWNdAVJRAT4+ASsrARgYAQgIFwAA0///Au/zAZGPAWNdAVJRAT4+ASsrARgYAQgIFwAA0v//Au/zAZGPAWNdAVJRAT4+ASsrARgYAQgIFwAA0f//Au/zAZGPAWNdAVJRAT4+ASsrARgYAQgIFwAA0f//Ac3OAmttAUpNATY6ASMnARAUAQgIFwAA0P//Ac3OAmttAUpNATY6ASMnARAUAQgIFwAAz///Ac3OAmttAUpNATY6ASMnARAUAQUFFwAAzv//Ac3OAmttAUpNATY6ASMnARAUAQUFFwAAzP//Aff7AcXJAmNlAUJFATEyASAfARAMAQUCFwAAy///Aff7AcXJAmNlAUJFATEyASAfARAMAQUCFwAAyv//Aff7AZSXAmNlAUJFATEyASAfARAMAQIBFwAAyf//Aff7AZSXAmNlAUJFATEyASAfARAMAQIBFwAAyP//Ad7jAoCBAVJRATk8ASgqARgZAQgIGAAAx///Ad7jAYCBAlJRATk8ASgqARgZAQgIGAAAxv//Ad7jAYCBAlJRATk8ASgqARgZAQgIGAAAxf//Ad7jAYCBAlJRATk8ASgqARgZAQgIGAAAxP//AcbHAnNwAUpFATEwASAgARAQGQAAw///AcbHAnNwAUpFATEwASAgARAQGQAAwv//AZybAXNwAkpFATEwASAgARAQGQAAwP//Afz9AZybAXNwAkpFATEwASAgARAQGQAAv///Ae7tAYyKAXBwAVRWATk8ASkoARsaAQ0NGQAAvv//Ae7tAYyKAXBwAVRWATk8ASkoARsaAQ0NGQAAvf//Ad7cAnBwAVRWATk8ASkoARsaAQ0NGQAAvP//Ac7LAXBwAlRWATk8ASkoARsaAQ0NGQAAuP//A//7AaenAWttAVdYAUREATEwASEgARYVAQsKGQAAt///A//7AaenAWttAVdYAUREATEwASEgAQsKGgAAtv//A//7AaenAWttAVdYAUREATEwASEgAQsKGgAAtf//A//7AXt9AWttAVdYAUREATEwARYVAQsKGgAAtv//AdDRAXN1AVpdAUdIATQ0ASEgARgUAQgGGgAAtf//AdDRAXN1AVpdAUdIATQ0ASEgARgUAQgGGgAAtP//AaGjAXN1AVpdAUdIATQ0ASEgARANAQgGGgAAs///AaGjAXN1AVpdAUdIATQ0ASEgARANGwAAsP//Avf7AZSUAWNhAUpNATY6AiMnARAMGwAAr///Avf7AZSUAWNhAUpNATY6ASMnARAUAQoIGwAArv//Aff7AcXHAmNhAUpNATY6ASMnARAUAQoIGwAArf//Aff7AcXHAmNhAUpNATY6ASMnARAUAQUEGwAArP//AffzAomHAVJRAUJBAS4uARsbAQgIAQAEGwAAq///AffzAYmHAlJRAUJBAS4uARsbAQgIAQABGwAAqv//AffzAYmHAlJRAUJBAS4uARsbAQgIHAAAqf//AcC9AYmHAlJRAS4uAhsbAQgIHAAAqP//AaWmAYGCAV1fATk8ASksARsdAQ0OHQAApv//Ae7tAYGCAl1fATk8ASksARsdAQ0OHQAApf//Ad7cAYGCAl1fATk8ASksARsdAQ0OHQAApP//Ac7LAYGCAl1fATk8ASksARsdAQ0OHQAAoP//A//7AaGhAWtpAVVTAT89ASkoASEgARYVHgAAn///A//7AaGhAWtpAVVTAT89ASkoASEgAQsKHgAAnv//Av/7AdDOAXN1AWtpAVVTAT89ASkoARYVAQsKHgAAnf//Av/7AdDOAXN1AWtpAVVTAT89ASkoARYVAQsKHgAAnP//Avf3AZSVAWNlAVJVAT4/AispARAQAQUFHgAAm///Avf3AZSVAWNlAVJVAT4/ASspARgUARAQHwAAmv//Aff3AcXGAmNlAVJVAT4/ASspARgUAQoKHwAAmf//Aff3AcXGAmNlAVJVAT4/ASspARgUAQUFHwAAmP//Ad7fAayuAXt9AUpNAUJBAS4sARsYAQgEAQAEHwAAl///Ad7fAnt9AUpNAUJBAS4sARsYAQgEAQABHwAAlv//AayuAXt9AkpNAUJBAS4sARsYAQgEIAAAlP//Aff3AayuAXt9AkpNAS4sAhsYAQgEIAAAk///AdbVAnN1AVpcAUFEASkoARsaAQ0NIQAAkv//AdbVAXN1AVpcAkFEASkoARsaAQ0NIQAAkf//Aa2rAXN1AVpcAUFEASksASkoAQ0NIgAAj///AdbVAYSCAXN1AVpcAUFEASksARsaAQ0NIgAAjP//Avf7AcjKAWtpAWNdAUpHAjExARgYAQgIIgAAi///Avf7AZmZAWtpAWNdAUpHATExARgcARAQAQgIIgAAiv//Avf7AmtpAkpHATExARgcARAQIwAAif//Aff7AcjKAmtpAUpHAjExARgcAQgIIwAAiP//',
    'Ad7jAayxAXt/AUpNAUJFAS4wAhscAQUFIwAAh///Ad7jAnt/AUpNAUJFAS4wARscAQgIAQICIwAAhv//AayxAXt/AkpNAi4wARscAQgIJAAAhP//AffzAayxAXt/AkpNAS4wAhscAQgIJAAAg///AdbVAXt5AWJfAklFASkkARsYAQ0MJQAAgv//Aa2rAXt5AWJfAUlFATEsASkkARsYAQ0MJQAAgP//AdbVAYSCAmJfAUlFATEsARsYAQ0MJgAAf///AdbVAYSCAWJfAUlFAjEsARsYAQ0MJgAAfP//Avf3AY6LAVpVAVJVAjw/ASYpARAQAQUFJgAAe///Aff3AcLBAY6LAVpVAVJVATw/ASYpARAUARAQAQUFJgAAev//Aff3AcLBAY6LAVpVAVJVATw/ASYpARAUAQoKJwAAef//Aff3AY6LAlpVATw/AiYpARAUAQUFJwAAeP//Ab26AmVmATk8ATk4ASYmAhMVKAAAdv//AePiAZGQAmVmATk8ATk4ASYmARMVAQAEKAAAdf//AcjGA2VmATk8ASYmAhMVAQAEKAAAdP//Aa2qAmVmAjk8ASYmARMVAgAEKAAAcv//Ac3LAWtlAWNlAkpLATExASEcAQsJKgAAcf//AZyYAWtlAWNlAUpLAjExARYSAQsJKgAAb///Ac3LAmtlAkpLATExARgYARYSKwAAbv//AZyYAmtlAUpLAjExARgYAQsJKwAAbP//Ad7fAnZ1AkJBAiwrARYVAQUFKwAAa///AaqqAnZ1AkJBASwrAhYVAQICKwAAaf//AenrAnZ1AkJBAiwrARYVLQAAaP//Ab3DAnZ1AkJBASwrAhYVLQAAZP//A/f3AZmYAWtlAk9MATM0ASEgARYVAQsKLQAAY///Avf3AcjHAWtpAWtlAU9MAjM0ASEgAQsKLgAAYv//Avf3AZmYAWtpAk9MATM0ARgcARYVAQsKLgAAYf//Aff3AcjHAmtpAU9MAjM0ARgcAQsKLwAAYP//Ad7fAnZyAUI8AUJBAiwsARYYAQgILwAAX///AaqoAnZyAUI8AUJBASwsAhYYAQICLwAAXf//AeblAnZyAkI8AiwsARYYAQAEMAAAXP//AbWyAnZyAkI8ASwsAhYYAQAEMAAAWv//Ac3NAWtpAmNlAUpLATExASEgARYVAQsKMQAAWf//AZybAWtpAWNlAUpLAjExARYVAQsKMgAAV///Ac3NAmtpAkpLATExARgYARYVAQsKMgAAVv//AZybAmtpAUpLAjExARgYAQsKMwAAVP//AcbDA2hmATk8AiYpARMWAQUFMwAAUv//AdjYAZeUAmhmATk4ATk8ASYpAhMWNAAAUf//AbKxA2hmATk4AiYpARMWAQAENAAAT///AdjYAYyKAmhmAjk4ASYpARMWAgAENAAATP//AvfzAcC+AYmJAlpZAUFCASgrARgYARAQNgAAS///AffzAcC+AYmJAVJVAVpZAUFCAigrARAQAQgINgAASv//AffzAomJAVJVAkFCASgrARAUARAQNwAASf//AcC+AYmJAlJVAUFCAigrARAUAQgINwAAR///AdDPAYSCAmVkAUdGATEwASAgAhAQOAAARv//AaGgAmVkAkdGATEwASAgARAQOQAARP//AdDPAXNxAWVkAkdGASkoASAgARAQOgAAQv//AdDPAnNxAWVkAUdGAikoASAgARAQOgAAQP//AefrAbCwAnl2AUpNAjQ2AR4fARAQAQUFOgAAP///AbCwAnl2AUI8AUpNATQ2Ah4fAQoKOwAAPf//AePiA3l2AUI8ATQ2Ah4fAQgIAQUFOwAAPP//Aa2qAnl2AkI8ATQ2AR4fAggIPAAAOP//Av/7AcjFAZGPAWNlAkpMATE0ASEgARYVAQsKPQAAN///Af/7AcjFAZGPAVpZAWNlAUpMAjE0ARYVAQsKPgAANv//Af/7AZGPAlpZAUpMAjE0ARgcARYVAQsKPgAANf//AcjFAZGPAlpZAUpMATE0AhgcAQsKPwAAMP//A//7AdDNAXt5Al1cAT9AATE0AiAiARARAQAEPwAAL///A//7AaGfAXt5AV1cAj9AATE0ASAiARARQQAALv//Av/7AaGfAXNxAl1cAj9AASAiAhARQQAALf//Af/7AdDNAnNxAV1cAj9AASEkAhARQgAAKP//BP/7Ac7LA2prAUpJAjEyARgbARAQAQUFQgAAJ///BP/7AZybAmprATk8AjEyAhgbAQUFQwAAJv//A//7AaekAmprAjk8ATEyAhgbAQAERAAAJf//Av/7AdPPAXt5AmprAjk8ATEyARgbAgAERAAAJP//Au/vAoGDAlJVATw+ASYnARgYARAQAQgIRQAAI///Ae/vAoGDAUpNAVJVATw+AiYnARAQAQgIRgAAIf//AebmAbi5AYGDAkpNATw+AiYnARAQAQgIRwAAIP//AbW2AYGDA0pNATw+ASYnAhAQSAAAHP//Av/7AcjFAZGPAWtpAk9PATM1ASkoARsaAQ0NSQAAG///Af/7AcjFAZGPAVpZAk9PAjM1ARsaAQ0NSgAAGv//AcjFAZGPAlpZAU9PAjM1ARgcAg0NSgAAGP//AefnAZGPA1pZAjM1AhgcAQ0NSwAAFP//A/fzAY6MAXN1AldaATw/ATEwASAgAhAQTAAAE///AvfzAcK/AY6MAldaAjw/AiAgARAQTQAAEv//AffzAcK/AY6MAVpZAVdaAjw/ASEkASAgARAQTgAAEP//Afz9AcK/AY6MAlpZAjw/AiEkARAQTwAAD///AcjJAXt5Al1cAT9AATk4AiYlARMSAQgITwAADf//AcjJAZGTAXt5AV1cAj9AAiYlARMSUQAAC///AcjJAZGTAVpdAV1cAj9AASEkASYlAhMSUQAACf//AcjJAZGTAlpdAz9AASEkAhMSUgAAB///Ac3NAYSGAmNlAUJEAjk8ASYoARMUAQgMAQIEUgAABf//Ac3NAZybAmNlAkJEATk8ASYoAhMUAQIEUwAAA///Ac3NAZybAWtpAWNlA0JEASYoAhMUVQAAAf//Ac3NAZybAmtpA0JEASEkAhMUVgAAAYyKAm1sAU9OAUJBAiwsARYYARAQAQUFVgAAAW1sAk9OAiwsAhYYAQUFVwAAAU9OATEwASwsAhYYAQAEWAAAATEwAhYYAgAEWAAAARAQAQUF/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA',
    '/wAA/wAA/wAA/wAA/wAA/wAA/wAAxAAA',
  ],
);
function decodeBase64(value)
{
  const binary = globalThis.atob(value);
  const bytes = new Uint8Array(binary.length);

  for (let index = 0; index < binary.length; index++)
  {
    bytes[index] = binary.charCodeAt(index);
  }

  return bytes;
}

function decodeBase64Chunks(values)
{
  const chunks = values.map(decodeBase64);
  const length = chunks.reduce((total, chunk) => total + chunk.length, 0);
  const output = new Uint8Array(length);
  let offset = 0;

  for (const chunk of chunks)
  {
    output.set(chunk, offset);
    offset += chunk.length;
  }

  return output;
}

function writeCirclePixel(output, x, y, red, green)
{
  const offset = (y * CIRCLE_TEXTURE_SIZE + x) * 4;

  output[offset] = red;
  output[offset + 1] = green;
  output[offset + 2] = red;
  output[offset + 3] = 255;
}

function decodeCircleTexture()
{
  const runs = decodeBase64Chunks(RUNS_BASE64_CHUNKS);
  const output = new Uint8Array(
    CIRCLE_TEXTURE_SIZE * CIRCLE_TEXTURE_SIZE * 4,
  );
  let runOffset = 0;
  let runRemaining = 0;
  let runRed = 0;
  let runGreen = 0;

  for (let y = 0; y < CIRCLE_TEXTURE_SIZE; y++)
  {
    for (let x = y; x < CIRCLE_TEXTURE_SIZE; x++)
    {
      if (runRemaining === 0)
      {
        if (runOffset + 2 >= runs.length)
        {
          throw new Error('Circle_01 RLE 数据提前结束');
        }

        runRemaining = runs[runOffset];
        runRed = runs[runOffset + 1];
        runGreen = runs[runOffset + 2];
        runOffset += 3;
      }

      writeCirclePixel(output, x, y, runRed, runGreen);

      if (x !== y)
      {
        writeCirclePixel(output, y, x, runRed, runGreen);
      }

      runRemaining--;
    }
  }

  if (runOffset !== runs.length || runRemaining !== 0)
  {
    throw new Error('Circle_01 RLE 数据长度不匹配');
  }

  return output;
}

function srgbByteToLinearByte(value)
{
  const normalized = value / 255;
  const linear = normalized <= 0.04045
    ? normalized / 12.92
    : ((normalized + 0.055) / 1.055) ** 2.4;

  return Math.round(linear * 255);
}

export const CIRCLE_TEXTURE_RGBA = decodeCircleTexture();

export function createCircleTextureSources(createCanvas)
{
  if (typeof createCanvas !== 'function')
  {
    return null;
  }

  const colorCanvas = createCanvas();
  const srgbColorCanvas = createCanvas();
  const coverageCanvas = createCanvas();

  colorCanvas.width = CIRCLE_TEXTURE_SIZE;
  colorCanvas.height = CIRCLE_TEXTURE_SIZE;
  srgbColorCanvas.width = CIRCLE_TEXTURE_SIZE;
  srgbColorCanvas.height = CIRCLE_TEXTURE_SIZE;
  coverageCanvas.width = CIRCLE_TEXTURE_SIZE;
  coverageCanvas.height = CIRCLE_TEXTURE_SIZE;

  const colorContext = colorCanvas.getContext('2d');
  const srgbColorContext = srgbColorCanvas.getContext('2d');
  const coverageContext = coverageCanvas.getContext('2d');

  if (
    !colorContext ||
    !srgbColorContext ||
    !coverageContext ||
    typeof colorContext.createImageData !== 'function' ||
    typeof srgbColorContext.createImageData !== 'function' ||
    typeof coverageContext.createImageData !== 'function'
  )
  {
    colorCanvas.width = 0;
    colorCanvas.height = 0;
    srgbColorCanvas.width = 0;
    srgbColorCanvas.height = 0;
    coverageCanvas.width = 0;
    coverageCanvas.height = 0;
    return null;
  }

  const colorImage = colorContext.createImageData(
    CIRCLE_TEXTURE_SIZE,
    CIRCLE_TEXTURE_SIZE,
  );
  const srgbColorImage = srgbColorContext.createImageData(
    CIRCLE_TEXTURE_SIZE,
    CIRCLE_TEXTURE_SIZE,
  );
  const coverageImage = coverageContext.createImageData(
    CIRCLE_TEXTURE_SIZE,
    CIRCLE_TEXTURE_SIZE,
  );

  for (let offset = 0; offset < CIRCLE_TEXTURE_RGBA.length; offset += 4)
  {
    const linearRed = srgbByteToLinearByte(CIRCLE_TEXTURE_RGBA[offset]);

    colorImage.data[offset] = linearRed;
    colorImage.data[offset + 1] = srgbByteToLinearByte(
      CIRCLE_TEXTURE_RGBA[offset + 1],
    );
    colorImage.data[offset + 2] = linearRed;
    colorImage.data[offset + 3] = 255;
    // DOM Add 没有后续 Linear -> sRGB Final Pass，保留原始采样值供其近似。
    srgbColorImage.data[offset] = CIRCLE_TEXTURE_RGBA[offset];
    srgbColorImage.data[offset + 1] = CIRCLE_TEXTURE_RGBA[offset + 1];
    srgbColorImage.data[offset + 2] = CIRCLE_TEXTURE_RGBA[offset + 2];
    srgbColorImage.data[offset + 3] = 255;
    coverageImage.data[offset] = 255;
    coverageImage.data[offset + 1] = 255;
    coverageImage.data[offset + 2] = 255;
    coverageImage.data[offset + 3] = linearRed;
  }

  colorContext.putImageData(colorImage, 0, 0);
  srgbColorContext.putImageData(srgbColorImage, 0, 0);
  coverageContext.putImageData(coverageImage, 0, 0);
  return {
    colorCanvas,
    srgbColorCanvas,
    coverageCanvas,
  };
}
